export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="antialiased bg-red-400" style={{ margin: 0, height: '100%' }}>
      <body style={{ boxSizing: 'border-box', margin: 0, padding: 0, height: '100%', outline: 'none' }}>{children}</body>
    </html>
  )
}
