import type { Metadata } from 'next'
import './global.css'

export const metadata: Metadata = {
  title: 'Home - Clickt',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="antialiased h-full m-0">
      <body className="box-border m-0 p-0 h-full outline-none">{children}</body>
    </html>
  )
}
