import type { Metadata } from 'next';
import { Josefin_Sans } from "next/font/google";
import { css, cx } from '../../styled-system/css';

import Navbar from '@/components/Navbar';
import './global.css';

export const metadata: Metadata = {
  title: 'Home - Clickt',
  description: 'Generated by Next.js',
}

export const josefinSans = Josefin_Sans({ weight: ['400', '700'], subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cx(josefinSans.className, css({ fontSmoothing: 'antialiased', overflow: 'hidden' }))}>
      <body className={css({ boxSizing: 'border-box', margin: 0, padding: 0, height: '100%', outline: 'none ' })}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
